#Load Data and N2V parameters
!pip install --upgrade networkx matplotlib
!pip install node2vec
!pip install umap-learn

import networkx as nx
import mathplotlib.pyplot as plt

# Load the graph into a varialble called books_graph using read_gml from the NetworkX library imported earlier
gml_graph = nx.read_gml('/PATH/TO/File.gml')
# Initializes the N2V model with specified parameters for the input graph
node2Vec = Node2Vec(books_graph, dimensions=64, walk_length=30, num_walks=200, workers=4)
# Trained the N2V model 
model = node2vec.fit(window=10, min_count=1, \batch_words=4)
# Extracts and stores the node embeddings generated by the N2V model in a dictionary
embeddings = {str(node): model.wv[str(node)]\ for node in gml_graph.nodes()}

